### ISSUE TITLE
Error while executing. this.wire -> undefined

### ISSUE THREAD

**Issue by ademcaliskan** [kd7yva/oled-js-pi#1]
Just tried this cool part of library, but no way, semms not to work. Whats going wrong?

TypeError?

`this.ADDRESS: 60
/home/pi/node_progs/myoled/node_modules/oled-js-pi/oled.js:121
    this.wire.writeByte(val, function(err) {
             ^
TypeError: Cannot read property 'writeByte' of undefined
  at /home/pi/node_progs/myoled/node_modules/oled-js-pi/oled.js:121:14
  at Immediate._onImmediate (/home/pi/node_progs/myoled/node_modules/oled-js-pi/node_modules/i2c/lib/i2c.coffee:60:9)
  at processImmediate [as _immediateCallback] (timers.js:358:17)
`

https://gist.github.com/ademcaliskan/33fe3bdd4407889a5857

**Comment by ademcaliskan** [comment]
Solved this by changing following function:

```
Oled.prototype._transfer = function(type, val, fn) {
  var control;
  if (type === 'data') {
    control = 0x40;
  } else if (type === 'cmd') {
    control = 0x00;
  } else {
    return;
  }

  // send control and actual val
  // this.board.io.i2cWrite(this.ADDRESS, [control, val]);
  this.i2c.writeBytes(control, [val], function(err) {});
}
```

**Comment by nonsintetic** [comment]
it will not work with the provided code, but it WILL work with this:

```
// writes both commands and data buffers to this device
Oled.prototype._transfer = function(type, val, fn) {
  var control;
  if (type === 'data') {
    control = 0x40;
  } else if (type === 'cmd') {
    control = 0x00;
  } else {
    return;
  }

  // send control and actual val
  // this.board.io.i2cWrite(this.ADDRESS, [control, val]);
  this.wire.writeBytes(control, [val], function(err) {});
}
```

i changed `this.i2c.writeBytes` to `this.wire.writeBytes`. Sure enough the screen jumped to life
