### ISSUE TITLE
Cannot read property 'writeByte' of undefined

### ISSUE THREAD

**Issue by srl295** [kd7yva/oled-js-pi#3]
the [sample code](https://github.com/kd7yva/oled-js-pi#i2c-example) gives me this error.

```
> TypeError: Cannot read property 'writeByte' of undefined
  at /home/pi/src/myoled/node_modules/oled-js-pi/oled.js:121:14
  at Immediate._onImmediate (/home/pi/src/myoled/node_modules/oled-js-pi/node_modules/i2c/lib/i2c.coffee:60:9)
  at processImmediate [as _immediateCallback] (timers.js:358:17)

```

"original" rPi model B. Adafruit 64x128 module. i2c. I can see the bus is opened properly and the address is set properly. Any ideas?  Perhaps the native module isn't loaded properly? No other errs.

I'll try manually calling the `i2c` library.

**Comment by srl295** [comment]
looks like it's a dup of #1 which was inexplicably closed

**Comment by dammianhr** [comment]
hello!
i have the same problem
but dont fix it.
any help?
`/home/pi/node_modules/oled-js-pi/oled.js:121
    this.wire.writeByte(val, function(err) {
             ^

TypeError: Cannot read property 'writeByte' of undefined
  at /home/pi/node_modules/oled-js-pi/oled.js:121:14
  at Immediate._onImmediate (/home/pi/node_modules/i2c/lib/i2c.coffee:60:9)
  at processImmediate [as _immediateCallback](timers.js:368:17)`

**Comment by srl295** [comment]
@dammianhr see https://github.com/kd7yva/oled-js-pi/issues/1#issuecomment-211797729 — I'll close this.
